### ISSUE TITLE
Scroll top is not working smoothly

### ISSUE THREAD

**Issue by ImanHasan** [Syknapse/Contribute-To-This-Project#2112]

**Comment by ImanHasan** [comment]
I would like to resolve this please assign this to me.

**Comment by TenTraicion** [comment]
what do you mean by not working properly? @ImanHasan

**Comment by win21H2** [comment]
@TenTraicion I think @ImanHasan is saying that the scroll to top button does not move up in a smooth fashion (e.g. a slow motion scroll).

If this is the case @ImanHasan, I will assign this PR to you but if you want to make any changes, please make a PR with a branch name of something like `scrollbar-smoother-ImanHasan` so that we can review and test it. 

Thanks,
win21H2
324Hz

**Comment by Syknapse** [comment]
Go for it. I would love to see a smooth scroll up 💪

**Comment by ImanHasan** [comment]
Yeah sure

**Comment by ZubairImtiaz3** [comment]
> Go for it. I would love to see a smooth scroll up 💪

Opening a PR resolving this issue. Take a look @Syknapse
