### ISSUE TITLE
PR not working

### ISSUE THREAD

**Issue by wboswall** [Syknapse/Contribute-To-This-Project#2529]
I have committed and pushed my card and updated to my add-wboswall-card but it went through, but I can't seem to find the change it didn't register in my fork.  Any help would be appreciated.  Thanks.

**Comment by win21H2** [comment]
Hello @wboswall, I cant seem to find any PR's with the name "add-wboswall-card". Could you please share a link to the PR? (maybe it got lost somewhere in the PR's because all I see is in the image below)

![image](https://user-images.githubusercontent.com/92825997/234162519-e4e56f66-d929-4550-96f9-91d50d917231.png)

Thanks,
win21H2
324Hz

**Comment by wboswall** [comment]
I refreshed the repo and added my contribution.  I then tried to add my branch add-wboswall-card but I can't because of the following error: 
C:\Users\User\Git\Contribute-To-This-Project>git status
fatal: detected dubious ownership in repository at 'C:/Users/User/Git/Contribute-To-This-Project'
'C:/Users/User/Git/Contribute-To-This-Project' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-2083998709-1698034328-3151938053-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/User/Git/Contribute-To-This-Project

**Comment by wboswall** [comment]
This time it worked, and my pull request went through.
